# -*- coding: utf-8 -*-
"""
Lista de dicionários com informação sobre pessoas famosas (atores, atletas,
cantores) e marcas conhecidas mundialmente.

Cada dicionário tem a seguinte estrutura:
{
    "name": str,          # nome da pessoa ou marca
    "followers": int,     # número aproximado de seguidores no Instagram
    "description": str,   # breve descrição
    "country": str        # país de origem
}

NOTA IMPORTANTE:
Os valores de "followers" são APROXIMADOS e arredondados. 
"""

data = [
    # ---------------- ATORES E ATRIZES ----------------
    {"name": "Dwayne Johnson", "followers": 396000000, "description": "Ator e ex-lutador de wrestling, um dos rostos mais conhecidos de Hollywood.", "country": "Estados Unidos"},
    {"name": "Selena Gomez", "followers": 428000000, "description": "Atriz e cantora, uma das figuras mais seguidas do mundo.", "country": "Estados Unidos"},
    {"name": "Kylie Jenner", "followers": 400000000, "description": "Empresária e figura mediática, fundadora de uma marca de cosmética.", "country": "Estados Unidos"},
    {"name": "Kim Kardashian", "followers": 364000000, "description": "Empresária e figura mediática, fundadora de marcas de beleza e vestuário.", "country": "Estados Unidos"},
    {"name": "Priyanka Chopra", "followers": 88000000, "description": "Atriz indiana com carreira internacional em Hollywood e Bollywood.", "country": "Índia"},
    {"name": "Vin Diesel", "followers": 105000000, "description": "Ator conhecido pela saga de filmes de ação sobre automobilismo.", "country": "Estados Unidos"},
    {"name": "Will Smith", "followers": 70000000, "description": "Ator e músico, protagonista de vários filmes de grande sucesso.", "country": "Estados Unidos"},
    {"name": "Zendaya", "followers": 185000000, "description": "Atriz norte-americana conhecida por séries e filmes de grande êxito.", "country": "Estados Unidos"},
    {"name": "Tom Holland", "followers": 68000000, "description": "Ator britânico conhecido por interpretar o super-herói Homem-Aranha.", "country": "Reino Unido"},
    {"name": "Robert Downey Jr.", "followers": 100000000, "description": "Ator conhecido por interpretar o Homem de Ferro no universo Marvel.", "country": "Estados Unidos"},
    {"name": "Scarlett Johansson", "followers": 25000000, "description": "Atriz norte-americana, uma das mais bem pagas de Hollywood.", "country": "Estados Unidos"},
    {"name": "Chris Hemsworth", "followers": 62000000, "description": "Ator australiano conhecido por interpretar Thor no universo Marvel.", "country": "Austrália"},
    {"name": "Emma Watson", "followers": 70000000, "description": "Atriz britânica conhecida pela saga cinematográfica Harry Potter.", "country": "Reino Unido"},
    {"name": "Jennifer Lopez", "followers": 250000000, "description": "Atriz, cantora e empresária norte-americana.", "country": "Estados Unidos"},
    {"name": "Reese Witherspoon", "followers": 28000000, "description": "Atriz e produtora norte-americana, vencedora de um Óscar.", "country": "Estados Unidos"},
    {"name": "Ryan Reynolds", "followers": 50000000, "description": "Ator canadiano conhecido pela comédia de ação Deadpool.", "country": "Canadá"},
    {"name": "Margot Robbie", "followers": 30000000, "description": "Atriz e produtora australiana, protagonista de vários filmes de sucesso.", "country": "Austrália"},
    {"name": "Leonardo DiCaprio", "followers": 62000000, "description": "Ator norte-americano vencedor de um Óscar, ativista ambiental.", "country": "Estados Unidos"},
    {"name": "Gal Gadot", "followers": 111000000, "description": "Atriz israelita conhecida por interpretar a Mulher-Maravilha.", "country": "Israel"},
    {"name": "Jason Statham", "followers": 55000000, "description": "Ator britânico conhecido por papéis em filmes de ação.", "country": "Reino Unido"},
    {"name": "Anne Hathaway", "followers": 32000000, "description": "Atriz norte-americana, vencedora de um Óscar.", "country": "Estados Unidos"},
    {"name": "Hugh Jackman", "followers": 30000000, "description": "Ator australiano conhecido por interpretar Wolverine.", "country": "Austrália"},
    {"name": "Millie Bobby Brown", "followers": 62000000, "description": "Atriz britânica conhecida pela série Stranger Things.", "country": "Reino Unido"},
    {"name": "Jamie Foxx", "followers": 20000000, "description": "Ator e músico norte-americano, vencedor de um Óscar.", "country": "Estados Unidos"},
    {"name": "Sofía Vergara", "followers": 32000000, "description": "Atriz colombiana conhecida pela série Modern Family.", "country": "Colômbia"},

    # ---------------- ATLETAS - FUTEBOL ----------------
    {"name": "Cristiano Ronaldo", "followers": 650000000, "description": "Futebolista português, um dos maiores marcadores de golos da história.", "country": "Portugal"},
    {"name": "Lionel Messi", "followers": 505000000, "description": "Futebolista argentino, considerado um dos melhores jogadores de sempre.", "country": "Argentina"},
    {"name": "Neymar Jr.", "followers": 220000000, "description": "Futebolista brasileiro conhecido pela sua técnica e criatividade.", "country": "Brasil"},
    {"name": "Kylian Mbappé", "followers": 130000000, "description": "Futebolista francês, atacante conhecido pela sua velocidade.", "country": "França"},
    {"name": "Erling Haaland", "followers": 40000000, "description": "Futebolista norueguês conhecido pela sua eficácia a marcar golos.", "country": "Noruega"},
    {"name": "Vinícius Júnior", "followers": 55000000, "description": "Futebolista brasileiro, extremo do Real Madrid.", "country": "Brasil"},
    {"name": "Sergio Ramos", "followers": 60000000, "description": "Futebolista espanhol, defesa-central experiente.", "country": "Espanha"},
    {"name": "Luka Modrić", "followers": 45000000, "description": "Futebolista croata, médio vencedor da Bola de Ouro.", "country": "Croácia"},
    {"name": "Robert Lewandowski", "followers": 35000000, "description": "Futebolista polaco, um dos melhores avançados da sua geração.", "country": "Polónia"},
    {"name": "Kevin De Bruyne", "followers": 20000000, "description": "Futebolista belga, médio conhecido pela sua visão de jogo.", "country": "Bélgica"},
    {"name": "Bruno Fernandes", "followers": 20000000, "description": "Futebolista português, médio ofensivo do Manchester United.", "country": "Portugal"},
    {"name": "João Félix", "followers": 20000000, "description": "Futebolista português, avançado conhecido pela sua técnica.", "country": "Portugal"},
    {"name": "Rúben Dias", "followers": 8000000, "description": "Futebolista português, defesa-central do Manchester City.", "country": "Portugal"},
    {"name": "Bernardo Silva", "followers": 10000000, "description": "Futebolista português, médio do Manchester City.", "country": "Portugal"},
    {"name": "Karim Benzema", "followers": 55000000, "description": "Futebolista francês, avançado vencedor da Bola de Ouro.", "country": "França"},
    {"name": "Mohamed Salah", "followers": 65000000, "description": "Futebolista egípcio, avançado do Liverpool.", "country": "Egito"},
    {"name": "Virgil van Dijk", "followers": 18000000, "description": "Futebolista neerlandês, defesa-central do Liverpool.", "country": "Países Baixos"},
    {"name": "Harry Kane", "followers": 15000000, "description": "Futebolista inglês, avançado conhecido pela sua finalização.", "country": "Reino Unido"},
    {"name": "Antoine Griezmann", "followers": 35000000, "description": "Futebolista francês, avançado do Atlético de Madrid.", "country": "França"},
    {"name": "Zlatan Ibrahimović", "followers": 55000000, "description": "Ex-futebolista sueco conhecido pelo seu carisma e golos espetaculares.", "country": "Suécia"},

    # ---------------- ATLETAS - BASQUETEBOL ----------------
    {"name": "LeBron James", "followers": 160000000, "description": "Jogador de basquetebol norte-americano, considerado um dos maiores de sempre.", "country": "Estados Unidos"},
    {"name": "Stephen Curry", "followers": 55000000, "description": "Jogador de basquetebol norte-americano, especialista em lançamentos de longa distância.", "country": "Estados Unidos"},
    {"name": "Kevin Durant", "followers": 30000000, "description": "Jogador de basquetebol norte-americano, um dos melhores marcadores da NBA.", "country": "Estados Unidos"},
    {"name": "Giannis Antetokounmpo", "followers": 20000000, "description": "Jogador de basquetebol grego, conhecido como 'The Greek Freak'.", "country": "Grécia"},
    {"name": "James Harden", "followers": 24000000, "description": "Jogador de basquetebol norte-americano, conhecido pela sua ofensiva.", "country": "Estados Unidos"},
    {"name": "Kobe Bryant", "followers": 20000000, "description": "Lenda do basquetebol norte-americano, vencedor de cinco títulos da NBA.", "country": "Estados Unidos"},
    {"name": "Luka Dončić", "followers": 15000000, "description": "Jogador de basquetebol esloveno, uma das estrelas mais jovens da NBA.", "country": "Eslovénia"},
    {"name": "Anthony Davis", "followers": 15000000, "description": "Jogador de basquetebol norte-americano dos Los Angeles Lakers.", "country": "Estados Unidos"},
    {"name": "Jayson Tatum", "followers": 10000000, "description": "Jogador de basquetebol norte-americano dos Boston Celtics.", "country": "Estados Unidos"},
    {"name": "Shaquille O'Neal", "followers": 20000000, "description": "Antigo jogador de basquetebol e comentador desportivo norte-americano.", "country": "Estados Unidos"},

    # ---------------- ATLETAS - TÉNIS, F1 E OUTROS ----------------
    {"name": "Rafael Nadal", "followers": 20000000, "description": "Tenista espanhol, vencedor de múltiplos títulos de Grand Slam.", "country": "Espanha"},
    {"name": "Novak Djokovic", "followers": 14000000, "description": "Tenista sérvio, um dos maiores da história do ténis.", "country": "Sérvia"},
    {"name": "Serena Williams", "followers": 17000000, "description": "Ex-tenista norte-americana, uma das maiores da história do desporto.", "country": "Estados Unidos"},
    {"name": "Lewis Hamilton", "followers": 35000000, "description": "Piloto britânico de Fórmula 1, multicampeão mundial.", "country": "Reino Unido"},
    {"name": "Max Verstappen", "followers": 12000000, "description": "Piloto neerlandês de Fórmula 1, campeão mundial.", "country": "Países Baixos"},
    {"name": "Michael Phelps", "followers": 14000000, "description": "Ex-nadador norte-americano, o atleta mais medalhado da história olímpica.", "country": "Estados Unidos"},
    {"name": "Usain Bolt", "followers": 11000000, "description": "Ex-velocista jamaicano, detentor de recordes mundiais nos 100m e 200m.", "country": "Jamaica"},
    {"name": "Simone Biles", "followers": 13000000, "description": "Ginasta norte-americana, uma das mais premiadas da história do desporto.", "country": "Estados Unidos"},
    {"name": "Conor McGregor", "followers": 50000000, "description": "Lutador irlandês de artes marciais mistas (MMA).", "country": "Irlanda"},
    {"name": "Floyd Mayweather", "followers": 30000000, "description": "Ex-pugilista norte-americano, invicto ao longo da carreira profissional.", "country": "Estados Unidos"},

    # ---------------- CANTORES E MÚSICOS ----------------
    {"name": "Ariana Grande", "followers": 380000000, "description": "Cantora e atriz norte-americana com vários êxitos musicais internacionais.", "country": "Estados Unidos"},
    {"name": "Taylor Swift", "followers": 280000000, "description": "Cantora e compositora norte-americana, uma das artistas mais influentes da atualidade.", "country": "Estados Unidos"},
    {"name": "Beyoncé", "followers": 320000000, "description": "Cantora, compositora e empresária norte-americana.", "country": "Estados Unidos"},
    {"name": "Justin Bieber", "followers": 293000000, "description": "Cantor canadiano com carreira internacional de grande sucesso.", "country": "Canadá"},
    {"name": "Rihanna", "followers": 150000000, "description": "Cantora e empresária de Barbados, fundadora de uma marca de cosmética.", "country": "Barbados"},
    {"name": "Shakira", "followers": 90000000, "description": "Cantora colombiana com carreira internacional de grande sucesso.", "country": "Colômbia"},
    {"name": "Ed Sheeran", "followers": 50000000, "description": "Cantor e compositor britânico conhecido pelas suas baladas.", "country": "Reino Unido"},
    {"name": "Katy Perry", "followers": 145000000, "description": "Cantora norte-americana com vários êxitos musicais.", "country": "Estados Unidos"},
    {"name": "Bruno Mars", "followers": 55000000, "description": "Cantor e produtor norte-americano conhecido pelo seu estilo funk e pop.", "country": "Estados Unidos"},
    {"name": "Billie Eilish", "followers": 120000000, "description": "Cantora norte-americana conhecida pelo seu estilo alternativo.", "country": "Estados Unidos"},
    {"name": "Dua Lipa", "followers": 90000000, "description": "Cantora britânica de origem albanesa, sucesso no género pop.", "country": "Reino Unido"},
    {"name": "Drake", "followers": 145000000, "description": "Rapper e cantor canadiano, um dos artistas mais vendidos do mundo.", "country": "Canadá"},
    {"name": "Bad Bunny", "followers": 45000000, "description": "Cantor porto-riquenho de reguetão e trap latino.", "country": "Porto Rico"},
    {"name": "Karol G", "followers": 68000000, "description": "Cantora colombiana de reguetão e música latina.", "country": "Colômbia"},
    {"name": "Shawn Mendes", "followers": 70000000, "description": "Cantor e compositor canadiano de pop.", "country": "Canadá"},
    {"name": "Camila Cabello", "followers": 62000000, "description": "Cantora cubano-americana, antiga integrante do grupo Fifth Harmony.", "country": "Cuba"},
    {"name": "Adele", "followers": 55000000, "description": "Cantora britânica conhecida pela sua voz poderosa e baladas.", "country": "Reino Unido"},
    {"name": "The Weeknd", "followers": 55000000, "description": "Cantor canadiano conhecido pelo estilo R&B contemporâneo.", "country": "Canadá"},
    {"name": "Nicki Minaj", "followers": 230000000, "description": "Rapper e cantora norte-americana de origem trinitária.", "country": "Trindade e Tobago"},
    {"name": "Anitta", "followers": 65000000, "description": "Cantora brasileira com carreira internacional de sucesso.", "country": "Brasil"},

    # ---------------- MARCAS ----------------
    {"name": "Nike", "followers": 305000000, "description": "Marca desportiva norte-americana de vestuário e calçado.", "country": "Estados Unidos"},
    {"name": "Adidas", "followers": 26000000, "description": "Marca desportiva alemã de vestuário e calçado.", "country": "Alemanha"},
    {"name": "Chanel", "followers": 60000000, "description": "Marca francesa de luxo, moda e perfumaria.", "country": "França"},
    {"name": "Gucci", "followers": 55000000, "description": "Marca italiana de luxo, moda e acessórios.", "country": "Itália"},
    {"name": "Louis Vuitton", "followers": 55000000, "description": "Marca francesa de luxo especializada em malas e acessórios.", "country": "França"},
    {"name": "National Geographic", "followers": 280000000, "description": "Marca dedicada a conteúdos de fotografia, natureza e ciência.", "country": "Estados Unidos"},
    {"name": "Victoria's Secret", "followers": 70000000, "description": "Marca norte-americana de lingerie e cosmética.", "country": "Estados Unidos"},
    {"name": "Zara", "followers": 55000000, "description": "Marca espanhola de vestuário e moda rápida.", "country": "Espanha"},
    {"name": "H&M", "followers": 38000000, "description": "Marca sueca de vestuário e moda acessível.", "country": "Suécia"},
    {"name": "Coca-Cola", "followers": 108000000, "description": "Marca norte-americana de bebidas, uma das mais reconhecidas do mundo.", "country": "Estados Unidos"},
    {"name": "Starbucks", "followers": 18000000, "description": "Marca norte-americana de cafetarias presente em todo o mundo.", "country": "Estados Unidos"},
    {"name": "McDonald's", "followers": 8000000, "description": "Marca norte-americana de restauração de fast food.", "country": "Estados Unidos"},
    {"name": "Ferrari", "followers": 27000000, "description": "Marca italiana de automóveis de luxo e desportivos.", "country": "Itália"},
    {"name": "BMW", "followers": 26000000, "description": "Marca alemã de automóveis de gama premium.", "country": "Alemanha"},
    {"name": "Mercedes-Benz", "followers": 24000000, "description": "Marca alemã de automóveis de luxo.", "country": "Alemanha"},
    {"name": "Apple", "followers": 26000000, "description": "Marca norte-americana de tecnologia, criadora do iPhone e Mac.", "country": "Estados Unidos"},
    {"name": "Samsung", "followers": 20000000, "description": "Marca sul-coreana de eletrónica e tecnologia.", "country": "Coreia do Sul"},
    {"name": "Puma", "followers": 15000000, "description": "Marca alemã de vestuário e calçado desportivo.", "country": "Alemanha"},
    {"name": "Louis Vuitton Moët Hennessy (LVMH)", "followers": 10000000, "description": "Grupo francês de marcas de luxo.", "country": "França"},
    {"name": "Prada", "followers": 20000000, "description": "Marca italiana de luxo, moda e acessórios.", "country": "Itália"},
    {"name": "Dior", "followers": 45000000, "description": "Marca francesa de luxo, moda e perfumaria.", "country": "França"},
    {"name": "Versace", "followers": 30000000, "description": "Marca italiana de luxo e alta-costura.", "country": "Itália"},
    {"name": "Burberry", "followers": 18000000, "description": "Marca britânica de luxo conhecida pelo seu padrão xadrez.", "country": "Reino Unido"},
    {"name": "Rolex", "followers": 15000000, "description": "Marca suíça de relógios de luxo.", "country": "Suíça"},
    {"name": "Red Bull", "followers": 12000000, "description": "Marca austríaca de bebidas energéticas.", "country": "Áustria"},

    # ---------------- OUTRAS FIGURAS PÚBLICAS ----------------
    {"name": "Oprah Winfrey", "followers": 20000000, "description": "Apresentadora, produtora e empresária norte-americana.", "country": "Estados Unidos"},
    {"name": "Elon Musk", "followers": 12000000, "description": "Empresário sul-africano, fundador da Tesla e da SpaceX.", "country": "África do Sul"},
    {"name": "Barack Obama", "followers": 36000000, "description": "Ex-presidente dos Estados Unidos da América.", "country": "Estados Unidos"},
    {"name": "MrBeast", "followers": 60000000, "description": "Criador de conteúdo norte-americano conhecido pelos seus desafios e doações.", "country": "Estados Unidos"},
    {"name": "Khaby Lame", "followers": 162000000, "description": "Criador de conteúdo italiano de origem senegalesa, popular pelo humor visual.", "country": "Itália"},
    {"name": "Cardi B", "followers": 165000000, "description": "Rapper e cantora norte-americana de origem dominicana e trinitária.", "country": "Estados Unidos"},
    {"name": "Kevin Hart", "followers": 178000000, "description": "Comediante e ator norte-americano.", "country": "Estados Unidos"},
    {"name": "Ellen DeGeneres", "followers": 135000000, "description": "Apresentadora e comediante norte-americana.", "country": "Estados Unidos"},

    # ---------------- MAIS ATORES E ATRIZES ----------------
    {"name": "Johnny Depp", "followers": 22000000, "description": "Ator norte-americano conhecido pela saga Piratas das Caraíbas.", "country": "Estados Unidos"},
    {"name": "Angelina Jolie", "followers": 19000000, "description": "Atriz e realizadora norte-americana, também ativista humanitária.", "country": "Estados Unidos"},
    {"name": "Brad Pitt", "followers": 9000000, "description": "Ator e produtor norte-americano, vencedor de um Óscar.", "country": "Estados Unidos"},
    {"name": "Tom Cruise", "followers": 10000000, "description": "Ator norte-americano conhecido pela saga Missão Impossível.", "country": "Estados Unidos"},
    {"name": "Sandra Bullock", "followers": 4000000, "description": "Atriz norte-americana vencedora de um Óscar.", "country": "Estados Unidos"},
    {"name": "Charlize Theron", "followers": 12000000, "description": "Atriz sul-africana vencedora de um Óscar.", "country": "África do Sul"},
    {"name": "Denzel Washington", "followers": 5000000, "description": "Ator norte-americano, vencedor de dois Óscares.", "country": "Estados Unidos"},
    {"name": "Morgan Freeman", "followers": 8000000, "description": "Ator norte-americano conhecido pela sua voz e presença de palco.", "country": "Estados Unidos"},
    {"name": "Natalie Portman", "followers": 12000000, "description": "Atriz norte-americana vencedora de um Óscar.", "country": "Estados Unidos"},
    {"name": "Emma Stone", "followers": 8000000, "description": "Atriz norte-americana vencedora de um Óscar.", "country": "Estados Unidos"},
    {"name": "Ryan Gosling", "followers": 500000, "description": "Ator canadiano conhecido por vários filmes de sucesso em Hollywood.", "country": "Canadá"},
    {"name": "Timothée Chalamet", "followers": 20000000, "description": "Ator norte-americano, uma das novas estrelas de Hollywood.", "country": "Estados Unidos"},
    {"name": "Florence Pugh", "followers": 27000000, "description": "Atriz britânica em ascensão em produções internacionais.", "country": "Reino Unido"},
    {"name": "Anya Taylor-Joy", "followers": 15000000, "description": "Atriz argentino-britânica conhecida pela série O Xadrez da Rainha.", "country": "Argentina"},
    {"name": "Pedro Pascal", "followers": 15000000, "description": "Ator chileno conhecido por séries como The Mandalorian e The Last of Us.", "country": "Chile"},
    {"name": "Jenna Ortega", "followers": 55000000, "description": "Atriz norte-americana conhecida pela série Wandinha.", "country": "Estados Unidos"},
    {"name": "Sydney Sweeney", "followers": 25000000, "description": "Atriz norte-americana em ascensão em séries e filmes recentes.", "country": "Estados Unidos"},
    {"name": "Michael B. Jordan", "followers": 20000000, "description": "Ator norte-americano conhecido pela saga Creed e Pantera Negra.", "country": "Estados Unidos"},
    {"name": "Idris Elba", "followers": 12000000, "description": "Ator britânico conhecido por papéis em cinema e televisão.", "country": "Reino Unido"},
    {"name": "Salma Hayek", "followers": 22000000, "description": "Atriz e produtora mexicana com carreira internacional.", "country": "México"},
    {"name": "Penélope Cruz", "followers": 8000000, "description": "Atriz espanhola vencedora de um Óscar.", "country": "Espanha"},
    {"name": "Antonio Banderas", "followers": 6000000, "description": "Ator espanhol com carreira internacional em Hollywood.", "country": "Espanha"},
    {"name": "Javier Bardem", "followers": 2000000, "description": "Ator espanhol vencedor de um Óscar.", "country": "Espanha"},
    {"name": "Cate Blanchett", "followers": 1000000, "description": "Atriz australiana, duas vezes vencedora do Óscar.", "country": "Austrália"},
    {"name": "Nicole Kidman", "followers": 12000000, "description": "Atriz australiana vencedora de um Óscar.", "country": "Austrália"},
    {"name": "Keanu Reeves", "followers": 0, "description": "Ator canadiano conhecido pelas sagas Matrix e John Wick.", "country": "Canadá"},
    {"name": "Chris Evans", "followers": 18000000, "description": "Ator norte-americano conhecido por interpretar o Capitão América.", "country": "Estados Unidos"},
    {"name": "Chris Pratt", "followers": 45000000, "description": "Ator norte-americano conhecido pela saga Guardiões da Galáxia.", "country": "Estados Unidos"},
    {"name": "Mark Wahlberg", "followers": 20000000, "description": "Ator e produtor norte-americano.", "country": "Estados Unidos"},
    {"name": "Adam Sandler", "followers": 12000000, "description": "Ator e comediante norte-americano.", "country": "Estados Unidos"},
    {"name": "Will Ferrell", "followers": 4000000, "description": "Ator e comediante norte-americano.", "country": "Estados Unidos"},
    {"name": "Steve Carell", "followers": 2000000, "description": "Ator e comediante norte-americano.", "country": "Estados Unidos"},
    {"name": "Awkwafina", "followers": 10000000, "description": "Atriz e comediante norte-americana de origem asiática.", "country": "Estados Unidos"},
    {"name": "Halle Berry", "followers": 6000000, "description": "Atriz norte-americana vencedora de um Óscar.", "country": "Estados Unidos"},
    {"name": "Viola Davis", "followers": 8000000, "description": "Atriz norte-americana vencedora de um Óscar.", "country": "Estados Unidos"},
    {"name": "Samuel L. Jackson", "followers": 10000000, "description": "Ator norte-americano com uma das carreiras mais prolíficas de Hollywood.", "country": "Estados Unidos"},
    {"name": "Matthew McConaughey", "followers": 9000000, "description": "Ator norte-americano vencedor de um Óscar.", "country": "Estados Unidos"},
    {"name": "Jake Gyllenhaal", "followers": 5000000, "description": "Ator norte-americano com uma carreira diversa no cinema.", "country": "Estados Unidos"},
    {"name": "Daniel Craig", "followers": 0, "description": "Ator britânico conhecido por interpretar o agente James Bond.", "country": "Reino Unido"},
    {"name": "Henry Cavill", "followers": 22000000, "description": "Ator britânico conhecido por interpretar Super-Homem e Geralt de Rívia.", "country": "Reino Unido"},

    # ---------------- MAIS FUTEBOLISTAS ----------------
    {"name": "Neymar", "followers": 220000000, "description": "Futebolista brasileiro conhecido pela sua técnica e criatividade.", "country": "Brasil"},
    {"name": "Paulo Dybala", "followers": 50000000, "description": "Futebolista argentino, avançado conhecido pela sua qualidade técnica.", "country": "Argentina"},
    {"name": "Ángel Di María", "followers": 25000000, "description": "Futebolista argentino, extremo com vasta experiência internacional.", "country": "Argentina"},
    {"name": "Gerard Piqué", "followers": 22000000, "description": "Ex-futebolista espanhol, defesa-central e empresário.", "country": "Espanha"},
    {"name": "Andrés Iniesta", "followers": 30000000, "description": "Ex-futebolista espanhol, médio histórico do FC Barcelona.", "country": "Espanha"},
    {"name": "Xavi Hernández", "followers": 12000000, "description": "Ex-futebolista e treinador espanhol, ícone do FC Barcelona.", "country": "Espanha"},
    {"name": "Pepe", "followers": 8000000, "description": "Futebolista português, defesa-central com longa carreira internacional.", "country": "Portugal"},
    {"name": "Diogo Dalot", "followers": 3000000, "description": "Futebolista português, lateral-direito do Manchester United.", "country": "Portugal"},
    {"name": "Rafael Leão", "followers": 12000000, "description": "Futebolista português, extremo do AC Milan.", "country": "Portugal"},
    {"name": "Diogo Jota", "followers": 10000000, "description": "Futebolista português, avançado do Liverpool.", "country": "Portugal"},
    {"name": "Pedro Neto", "followers": 4000000, "description": "Futebolista português, extremo do Chelsea.", "country": "Portugal"},
    {"name": "Nuno Mendes", "followers": 5000000, "description": "Futebolista português, lateral-esquerdo do Paris Saint-Germain.", "country": "Portugal"},
    {"name": "William Carvalho", "followers": 2000000, "description": "Futebolista português, médio com longa carreira em várias ligas europeias.", "country": "Portugal"},
    {"name": "José Mourinho", "followers": 20000000, "description": "Treinador de futebol português, um dos mais conceituados do mundo.", "country": "Portugal"},
    {"name": "Fernando Santos", "followers": 500000, "description": "Treinador de futebol português, antigo selecionador nacional.", "country": "Portugal"},
    {"name": "Eusébio", "followers": 400000, "description": "Página de memória do lendário futebolista português, um dos maiores da história.", "country": "Portugal"},
    {"name": "Kaká", "followers": 25000000, "description": "Ex-futebolista brasileiro, vencedor da Bola de Ouro em 2007.", "country": "Brasil"},
    {"name": "Ronaldinho", "followers": 55000000, "description": "Ex-futebolista brasileiro, conhecido pelo seu talento e ginga.", "country": "Brasil"},
    {"name": "Ronaldo Fenômeno", "followers": 25000000, "description": "Ex-futebolista brasileiro, considerado um dos maiores avançados de sempre.", "country": "Brasil"},
    {"name": "Casemiro", "followers": 25000000, "description": "Futebolista brasileiro, médio defensivo do Manchester United.", "country": "Brasil"},
    {"name": "Thiago Silva", "followers": 15000000, "description": "Futebolista brasileiro, defesa-central com vasta experiência europeia.", "country": "Brasil"},
    {"name": "Alisson Becker", "followers": 12000000, "description": "Futebolista brasileiro, guarda-redes do Liverpool.", "country": "Brasil"},
    {"name": "Ederson", "followers": 7000000, "description": "Futebolista brasileiro, guarda-redes do Manchester City.", "country": "Brasil"},
    {"name": "Son Heung-min", "followers": 10000000, "description": "Futebolista sul-coreano, avançado do Tottenham Hotspur.", "country": "Coreia do Sul"},
    {"name": "Sadio Mané", "followers": 25000000, "description": "Futebolista senegalês, avançado com passagem por vários clubes europeus.", "country": "Senegal"},
    {"name": "Riyad Mahrez", "followers": 20000000, "description": "Futebolista argelino, extremo conhecido pela sua técnica.", "country": "Argélia"},
    {"name": "N'Golo Kanté", "followers": 12000000, "description": "Futebolista francês, médio conhecido pela sua capacidade defensiva.", "country": "França"},
    {"name": "Paul Pogba", "followers": 55000000, "description": "Futebolista francês, médio conhecido pela sua versatilidade.", "country": "França"},
    {"name": "Raheem Sterling", "followers": 15000000, "description": "Futebolista britânico, extremo com passagem por vários clubes ingleses.", "country": "Reino Unido"},
    {"name": "Jude Bellingham", "followers": 30000000, "description": "Futebolista britânico, médio do Real Madrid.", "country": "Reino Unido"},

    # ---------------- MAIS BASQUETEBOLISTAS ----------------
    {"name": "Michael Jordan", "followers": 0, "description": "Lenda do basquetebol norte-americano, considerado o maior jogador da história.", "country": "Estados Unidos"},
    {"name": "Damian Lillard", "followers": 8000000, "description": "Jogador de basquetebol norte-americano conhecido pelos lançamentos decisivos.", "country": "Estados Unidos"},
    {"name": "Kyrie Irving", "followers": 20000000, "description": "Jogador de basquetebol norte-americano conhecido pelo seu drible.", "country": "Estados Unidos"},
    {"name": "Joel Embiid", "followers": 8000000, "description": "Jogador de basquetebol camaronês-americano dos Philadelphia 76ers.", "country": "Camarões"},
    {"name": "Nikola Jokić", "followers": 3000000, "description": "Jogador de basquetebol sérvio, considerado um dos melhores da atualidade.", "country": "Sérvia"},
    {"name": "Devin Booker", "followers": 12000000, "description": "Jogador de basquetebol norte-americano dos Phoenix Suns.", "country": "Estados Unidos"},
    {"name": "Klay Thompson", "followers": 10000000, "description": "Jogador de basquetebol norte-americano, especialista em lançamentos de três pontos.", "country": "Estados Unidos"},
    {"name": "Draymond Green", "followers": 6000000, "description": "Jogador de basquetebol norte-americano dos Golden State Warriors.", "country": "Estados Unidos"},
    {"name": "Russell Westbrook", "followers": 15000000, "description": "Jogador de basquetebol norte-americano conhecido pela sua energia em campo.", "country": "Estados Unidos"},
    {"name": "Dwyane Wade", "followers": 16000000, "description": "Ex-jogador de basquetebol norte-americano, campeão da NBA.", "country": "Estados Unidos"},

    # ---------------- OUTROS ATLETAS ----------------
    {"name": "Kelly Slater", "followers": 3000000, "description": "Surfista norte-americano, um dos maiores campeões da modalidade.", "country": "Estados Unidos"},
    {"name": "Tony Hawk", "followers": 12000000, "description": "Skatista norte-americano, lenda do skate profissional.", "country": "Estados Unidos"},
    {"name": "Valentino Rossi", "followers": 15000000, "description": "Ex-piloto italiano de motociclismo, nove vezes campeão mundial.", "country": "Itália"},
    {"name": "Marc Márquez", "followers": 8000000, "description": "Piloto espanhol de motociclismo, multicampeão mundial de MotoGP.", "country": "Espanha"},
    {"name": "Fernando Alonso", "followers": 10000000, "description": "Piloto espanhol de Fórmula 1, bicampeão mundial.", "country": "Espanha"},
    {"name": "Sebastian Vettel", "followers": 8000000, "description": "Ex-piloto alemão de Fórmula 1, tetracampeão mundial.", "country": "Alemanha"},
    {"name": "Carlos Alcaraz", "followers": 12000000, "description": "Tenista espanhol, uma das novas estrelas do ténis mundial.", "country": "Espanha"},
    {"name": "Iga Świątek", "followers": 3000000, "description": "Tenista polaca, número um do ranking mundial feminino.", "country": "Polónia"},
    {"name": "Naomi Osaka", "followers": 3000000, "description": "Tenista japonesa, vencedora de vários títulos de Grand Slam.", "country": "Japão"},
    {"name": "Roger Federer", "followers": 15000000, "description": "Ex-tenista suíço, considerado um dos maiores da história do ténis.", "country": "Suíça"},
    {"name": "Andy Murray", "followers": 3000000, "description": "Tenista britânico, ex-número um do ranking mundial.", "country": "Reino Unido"},
    {"name": "Katie Ledecky", "followers": 2000000, "description": "Nadadora norte-americana, múltipla campeã olímpica.", "country": "Estados Unidos"},
    {"name": "Caeleb Dressel", "followers": 1000000, "description": "Nadador norte-americano, múltiplo campeão olímpico.", "country": "Estados Unidos"},
    {"name": "Allyson Felix", "followers": 1000000, "description": "Ex-velocista norte-americana, múltipla medalhada olímpica.", "country": "Estados Unidos"},
    {"name": "Eliud Kipchoge", "followers": 3000000, "description": "Fundista queniano, recordista mundial da maratona.", "country": "Quénia"},

    # ---------------- MAIS CANTORES E MÚSICOS ----------------
    {"name": "Miley Cyrus", "followers": 200000000, "description": "Cantora e atriz norte-americana com carreira musical de destaque.", "country": "Estados Unidos"},
    {"name": "Lady Gaga", "followers": 60000000, "description": "Cantora e atriz norte-americana conhecida pelo seu estilo extravagante.", "country": "Estados Unidos"},
    {"name": "Post Malone", "followers": 20000000, "description": "Cantor e rapper norte-americano com vários êxitos musicais.", "country": "Estados Unidos"},
    {"name": "Travis Scott", "followers": 55000000, "description": "Rapper e produtor norte-americano.", "country": "Estados Unidos"},
    {"name": "Kanye West", "followers": 0, "description": "Rapper e produtor norte-americano, também estilista.", "country": "Estados Unidos"},
    {"name": "Jay-Z", "followers": 5000000, "description": "Rapper e empresário norte-americano, um dos mais influentes da indústria musical.", "country": "Estados Unidos"},
    {"name": "Eminem", "followers": 35000000, "description": "Rapper norte-americano, um dos artistas mais vendidos da história.", "country": "Estados Unidos"},
    {"name": "Snoop Dogg", "followers": 75000000, "description": "Rapper norte-americano com uma carreira de décadas na música.", "country": "Estados Unidos"},
    {"name": "50 Cent", "followers": 32000000, "description": "Rapper e ator norte-americano.", "country": "Estados Unidos"},
    {"name": "Chris Brown", "followers": 135000000, "description": "Cantor norte-americano conhecido pelo seu estilo R&B e dança.", "country": "Estados Unidos"},
    {"name": "Usher", "followers": 20000000, "description": "Cantor norte-americano de R&B com uma carreira de várias décadas.", "country": "Estados Unidos"},
    {"name": "John Legend", "followers": 13000000, "description": "Cantor e compositor norte-americano de R&B e soul.", "country": "Estados Unidos"},
    {"name": "Alicia Keys", "followers": 30000000, "description": "Cantora e pianista norte-americana de R&B e soul.", "country": "Estados Unidos"},
    {"name": "Sam Smith", "followers": 15000000, "description": "Cantor britânico conhecido pela sua voz e baladas emotivas.", "country": "Reino Unido"},
    {"name": "Harry Styles", "followers": 50000000, "description": "Cantor britânico, ex-integrante da banda One Direction.", "country": "Reino Unido"},
    {"name": "Niall Horan", "followers": 30000000, "description": "Cantor irlandês, ex-integrante da banda One Direction.", "country": "Irlanda"},
    {"name": "Liam Payne", "followers": 30000000, "description": "Ex-cantor britânico, ex-integrante da banda One Direction.", "country": "Reino Unido"},
    {"name": "Zayn Malik", "followers": 30000000, "description": "Cantor britânico, ex-integrante da banda One Direction.", "country": "Reino Unido"},
    {"name": "Charlie Puth", "followers": 20000000, "description": "Cantor e produtor norte-americano de pop.", "country": "Estados Unidos"},
    {"name": "Olivia Rodrigo", "followers": 40000000, "description": "Cantora norte-americana revelação do pop-rock.", "country": "Estados Unidos"},
    {"name": "Doja Cat", "followers": 25000000, "description": "Cantora e rapper norte-americana de pop e hip-hop.", "country": "Estados Unidos"},
    {"name": "SZA", "followers": 18000000, "description": "Cantora norte-americana de R&B alternativo.", "country": "Estados Unidos"},
    {"name": "Lizzo", "followers": 13000000, "description": "Cantora norte-americana conhecida pelo seu estilo pop e soul.", "country": "Estados Unidos"},
    {"name": "Maluma", "followers": 65000000, "description": "Cantor colombiano de reguetão e música latina.", "country": "Colômbia"},
    {"name": "J Balvin", "followers": 60000000, "description": "Cantor colombiano de reguetão, um dos pioneiros do género globalmente.", "country": "Colômbia"},
    {"name": "Ozuna", "followers": 65000000, "description": "Cantor porto-riquenho de reguetão e música urbana latina.", "country": "Porto Rico"},
    {"name": "Daddy Yankee", "followers": 45000000, "description": "Cantor porto-riquenho, considerado o 'rei do reguetão'.", "country": "Porto Rico"},
    {"name": "Enrique Iglesias", "followers": 32000000, "description": "Cantor espanhol com uma carreira internacional de sucesso.", "country": "Espanha"},
    {"name": "Luis Fonsi", "followers": 20000000, "description": "Cantor porto-riquenho, conhecido pelo êxito mundial 'Despacito'.", "country": "Porto Rico"},
    {"name": "Marília Mendonça", "followers": 30000000, "description": "Página de memória da cantora brasileira de música sertaneja.", "country": "Brasil"},
    {"name": "Ivete Sangalo", "followers": 40000000, "description": "Cantora brasileira, uma das maiores figuras do carnaval e do axé.", "country": "Brasil"},
    {"name": "Gusttavo Lima", "followers": 40000000, "description": "Cantor brasileiro de música sertaneja.", "country": "Brasil"},
    {"name": "Wesley Safadão", "followers": 45000000, "description": "Cantor brasileiro de forró e música eletrónica.", "country": "Brasil"},
    {"name": "Luísa Sonza", "followers": 30000000, "description": "Cantora brasileira de pop e música urbana.", "country": "Brasil"},
    {"name": "Mariza", "followers": 500000, "description": "Fadista portuguesa reconhecida internacionalmente.", "country": "Portugal"},
    {"name": "Salvador Sobral", "followers": 200000, "description": "Cantor português, vencedor do Festival Eurovisão da Canção 2017.", "country": "Portugal"},
    {"name": "Mickael Carreira", "followers": 500000, "description": "Cantor português de música popular.", "country": "Portugal"},
    {"name": "Ana Moura", "followers": 400000, "description": "Fadista portuguesa com projeção internacional.", "country": "Portugal"},
    {"name": "David Carreira", "followers": 700000, "description": "Cantor e ator português.", "country": "Portugal"},
    {"name": "Diogo Piçarra", "followers": 900000, "description": "Cantor português de pop, ex-participante de talent shows.", "country": "Portugal"},

    # ---------------- MAIS MARCAS ----------------
    {"name": "Balenciaga", "followers": 18000000, "description": "Marca espanhola de luxo e alta-costura com sede em Paris.", "country": "Espanha"},
    {"name": "Fendi", "followers": 13000000, "description": "Marca italiana de luxo, moda e acessórios.", "country": "Itália"},
    {"name": "Hermès", "followers": 16000000, "description": "Marca francesa de luxo conhecida pelas suas malas Birkin.", "country": "França"},
    {"name": "Cartier", "followers": 20000000, "description": "Marca francesa de joalharia e relógios de luxo.", "country": "França"},
    {"name": "Tiffany & Co.", "followers": 13000000, "description": "Marca norte-americana de joalharia de luxo.", "country": "Estados Unidos"},
    {"name": "Armani", "followers": 15000000, "description": "Marca italiana de moda de luxo fundada por Giorgio Armani.", "country": "Itália"},
    {"name": "Dolce & Gabbana", "followers": 25000000, "description": "Marca italiana de luxo e alta-costura.", "country": "Itália"},
    {"name": "Calvin Klein", "followers": 20000000, "description": "Marca norte-americana de moda e vestuário.", "country": "Estados Unidos"},
    {"name": "Levi's", "followers": 6000000, "description": "Marca norte-americana de vestuário, criadora das calças de ganga.", "country": "Estados Unidos"},
    {"name": "Under Armour", "followers": 8000000, "description": "Marca norte-americana de vestuário e calçado desportivo.", "country": "Estados Unidos"},
    {"name": "New Balance", "followers": 6000000, "description": "Marca norte-americana de calçado desportivo.", "country": "Estados Unidos"},
    {"name": "Converse", "followers": 18000000, "description": "Marca norte-americana de calçado casual, famosa pelo modelo All Star.", "country": "Estados Unidos"},
    {"name": "Vans", "followers": 15000000, "description": "Marca norte-americana de calçado ligada à cultura skate.", "country": "Estados Unidos"},
    {"name": "Reebok", "followers": 6000000, "description": "Marca norte-americana de vestuário e calçado desportivo.", "country": "Estados Unidos"},
    {"name": "Lacoste", "followers": 10000000, "description": "Marca francesa de vestuário conhecida pelo seu logótipo de crocodilo.", "country": "França"},
    {"name": "Tommy Hilfiger", "followers": 18000000, "description": "Marca norte-americana de moda casual e clássica.", "country": "Estados Unidos"},
    {"name": "Ralph Lauren", "followers": 15000000, "description": "Marca norte-americana de moda de luxo casual.", "country": "Estados Unidos"},
    {"name": "Pepsi", "followers": 5000000, "description": "Marca norte-americana de bebidas, concorrente direta da Coca-Cola.", "country": "Estados Unidos"},
    {"name": "Fanta", "followers": 12000000, "description": "Marca de refrigerantes com sabores de fruta, propriedade da Coca-Cola.", "country": "Estados Unidos"},
    {"name": "Heineken", "followers": 10000000, "description": "Marca neerlandesa de cerveja, distribuída em todo o mundo.", "country": "Países Baixos"},
    {"name": "Super Bock", "followers": 300000, "description": "Marca portuguesa de cerveja, uma das mais populares em Portugal.", "country": "Portugal"},
    {"name": "Sagres", "followers": 250000, "description": "Marca portuguesa de cerveja com forte presença no mercado nacional.", "country": "Portugal"},
    {"name": "Delta Cafés", "followers": 200000, "description": "Marca portuguesa de café, líder no mercado nacional.", "country": "Portugal"},
    {"name": "Continente", "followers": 300000, "description": "Marca portuguesa de distribuição alimentar e retalho.", "country": "Portugal"},
    {"name": "Galp", "followers": 150000, "description": "Marca portuguesa de energia e combustíveis.", "country": "Portugal"},
    {"name": "TAP Air Portugal", "followers": 500000, "description": "Companhia aérea de bandeira portuguesa.", "country": "Portugal"},
    {"name": "Meo", "followers": 200000, "description": "Marca portuguesa de telecomunicações e televisão por subscrição.", "country": "Portugal"},
    {"name": "NOS", "followers": 180000, "description": "Marca portuguesa de telecomunicações.", "country": "Portugal"},
    {"name": "Vodafone", "followers": 8000000, "description": "Marca britânica de telecomunicações com operações em Portugal e no mundo.", "country": "Reino Unido"},
    {"name": "Sporting Clube de Portugal", "followers": 4000000, "description": "Clube de futebol português, um dos três grandes do país.", "country": "Portugal"},
    {"name": "SL Benfica", "followers": 8000000, "description": "Clube de futebol português, o mais titulado do país.", "country": "Portugal"},
    {"name": "FC Porto", "followers": 6000000, "description": "Clube de futebol português com várias conquistas europeias.", "country": "Portugal"},
    {"name": "Real Madrid", "followers": 175000000, "description": "Clube de futebol espanhol, um dos mais titulados do mundo.", "country": "Espanha"},
    {"name": "FC Barcelona", "followers": 125000000, "description": "Clube de futebol espanhol, conhecido pelo seu estilo de jogo.", "country": "Espanha"},
    {"name": "Manchester United", "followers": 78000000, "description": "Clube de futebol inglês, um dos mais populares do mundo.", "country": "Reino Unido"},
    {"name": "Paris Saint-Germain", "followers": 60000000, "description": "Clube de futebol francês, com investimento e presença internacional crescente.", "country": "França"},
    {"name": "Liverpool FC", "followers": 60000000, "description": "Clube de futebol inglês com forte tradição europeia.", "country": "Reino Unido"},
    {"name": "Manchester City", "followers": 50000000, "description": "Clube de futebol inglês, campeão europeu recente.", "country": "Reino Unido"},
    {"name": "Juventus", "followers": 60000000, "description": "Clube de futebol italiano, o mais titulado da Serie A.", "country": "Itália"},
    {"name": "AC Milan", "followers": 30000000, "description": "Clube de futebol italiano com grande história europeia.", "country": "Itália"},
    {"name": "Bayern de Munique", "followers": 45000000, "description": "Clube de futebol alemão, o mais dominante da Bundesliga.", "country": "Alemanha"},
    {"name": "NBA", "followers": 80000000, "description": "Principal liga de basquetebol profissional dos Estados Unidos.", "country": "Estados Unidos"},
    {"name": "FIFA", "followers": 40000000, "description": "Federação Internacional de Futebol, entidade máxima do desporto.", "country": "Suíça"},
    {"name": "UEFA Champions League", "followers": 90000000, "description": "Principal competição de clubes de futebol da Europa.", "country": "Suíça"},

    # ---------------- CRIADORES DE CONTEÚDO E OUTRAS FIGURAS ----------------
    {"name": "PewDiePie", "followers": 20000000, "description": "Criador de conteúdo sueco, um dos pioneiros do YouTube.", "country": "Suécia"},
    {"name": "Charli D'Amelio", "followers": 160000000, "description": "Criadora de conteúdo e dançarina norte-americana, popular no TikTok.", "country": "Estados Unidos"},
    {"name": "Addison Rae", "followers": 88000000, "description": "Criadora de conteúdo e atriz norte-americana.", "country": "Estados Unidos"},
    {"name": "Bella Poarch", "followers": 92000000, "description": "Criadora de conteúdo e cantora norte-americana de origem filipina.", "country": "Estados Unidos"},
    {"name": "Emma Chamberlain", "followers": 16000000, "description": "Criadora de conteúdo e apresentadora norte-americana.", "country": "Estados Unidos"},
    {"name": "James Charles", "followers": 40000000, "description": "Criador de conteúdo norte-americano especializado em maquilhagem.", "country": "Estados Unidos"},
    {"name": "Huda Kattan", "followers": 55000000, "description": "Empresária e influenciadora norte-americana, fundadora da marca Huda Beauty.", "country": "Estados Unidos"},
    {"name": "Jeffree Star", "followers": 16000000, "description": "Criador de conteúdo e empresário norte-americano de cosmética.", "country": "Estados Unidos"},

    # ---------------- MOÇAMBIQUE - POLÍTICA E HISTÓRIA ----------------
    {"name": "Samora Machel", "followers": 300000, "description": "Primeiro Presidente de Moçambique após a independência, figura histórica da libertação nacional.", "country": "Moçambique"},
    {"name": "Josina Machel", "followers": 50000, "description": "Ativista política moçambicana, figura histórica da luta pela independência.", "country": "Moçambique"},
    {"name": "Graça Machel", "followers": 400000, "description": "Ativista moçambicana pelos direitos das crianças, antiga primeira-dama de Moçambique e da África do Sul.", "country": "Moçambique"},
    {"name": "Joaquim Chissano", "followers": 150000, "description": "Antigo Presidente da República de Moçambique.", "country": "Moçambique"},
    {"name": "Armando Guebuza", "followers": 100000, "description": "Antigo Presidente da República de Moçambique.", "country": "Moçambique"},
    {"name": "Filipe Nyusi", "followers": 300000, "description": "Antigo Presidente da República de Moçambique, em funções até janeiro de 2025.", "country": "Moçambique"},
    {"name": "Daniel Chapo", "followers": 250000, "description": "Presidente da República de Moçambique desde janeiro de 2025.", "country": "Moçambique"},
    {"name": "Eduardo Mondlane", "followers": 80000, "description": "Fundador e primeiro presidente da FRELIMO, figura histórica da luta pela independência.", "country": "Moçambique"},

    # ---------------- MOÇAMBIQUE - ESCRITORES E ARTISTAS ----------------
    {"name": "Mia Couto", "followers": 200000, "description": "Escritor moçambicano, um dos maiores nomes da literatura de língua portuguesa.", "country": "Moçambique"},
    {"name": "José Craveirinha", "followers": 30000, "description": "Poeta moçambicano, figura histórica da literatura nacional.", "country": "Moçambique"},
    {"name": "Paulina Chiziane", "followers": 40000, "description": "Escritora moçambicana, primeira mulher a publicar um romance no país.", "country": "Moçambique"},
    {"name": "Luís Bernardo Honwana", "followers": 15000, "description": "Escritor moçambicano de contos, referência da literatura pós-colonial.", "country": "Moçambique"},
    {"name": "Ungulani Ba Ka Khosa", "followers": 12000, "description": "Escritor e romancista moçambicano.", "country": "Moçambique"},
    {"name": "Lília Momplé", "followers": 8000, "description": "Escritora moçambicana de ficção.", "country": "Moçambique"},
    {"name": "Malangatana Ngwenya", "followers": 20000, "description": "Pintor e poeta moçambicano, um dos maiores artistas plásticos africanos.", "country": "Moçambique"},

    # ---------------- MOÇAMBIQUE - ATORES ----------------
    {"name": "Arlete Bombe", "followers": 30000, "description": "Atriz moçambicana de cinema e televisão.", "country": "Moçambique"},
    {"name": "Alberto Magassela", "followers": 15000, "description": "Ator moçambicano de cinema e teatro.", "country": "Moçambique"},
    {"name": "Rogério Manjate", "followers": 20000, "description": "Ator, escritor e realizador moçambicano.", "country": "Moçambique"},
    {"name": "Gilberto Mendes", "followers": 10000, "description": "Ator moçambicano de cinema e televisão.", "country": "Moçambique"},
    {"name": "Lucrécia Paco", "followers": 12000, "description": "Atriz moçambicana de cinema e teatro.", "country": "Moçambique"},

    # ---------------- MOÇAMBIQUE - MÚSICOS ----------------
    {"name": "Mr Bow", "followers": 500000, "description": "Cantor moçambicano de pandza, um dos artistas mais populares do país.", "country": "Moçambique"},
    {"name": "Lizha James", "followers": 400000, "description": "Cantora moçambicana, conhecida como a 'Rainha do Pandza'.", "country": "Moçambique"},
    {"name": "Neyma", "followers": 250000, "description": "Cantora moçambicana de R&B e afrobeat.", "country": "Moçambique"},
    {"name": "Dama do Bling", "followers": 350000, "description": "Cantora moçambicana de afro-pop e R&B.", "country": "Moçambique"},
    {"name": "Ziqo", "followers": 300000, "description": "Cantor moçambicano de pandza e afrobeat.", "country": "Moçambique"},
    {"name": "Denny Og", "followers": 200000, "description": "Cantor moçambicano de afro-pop e R&B.", "country": "Moçambique"},
    {"name": "Yannick Afroman", "followers": 250000, "description": "Cantor moçambicano de afrobeat e pandza.", "country": "Moçambique"},
    {"name": "Hernâni da Silva", "followers": 100000, "description": "Cantor e compositor moçambicano.", "country": "Moçambique"},
    {"name": "Marllen", "followers": 200000, "description": "Cantora moçambicana de afro-pop.", "country": "Moçambique"},
    {"name": "Wazimbo", "followers": 40000, "description": "Cantor moçambicano de marrabenta, um dos pioneiros do género.", "country": "Moçambique"},
    {"name": "Stewart Sukuma", "followers": 30000, "description": "Cantor e compositor moçambicano de world music.", "country": "Moçambique"},
    {"name": "Mingas", "followers": 15000, "description": "Cantora moçambicana histórica de marrabenta.", "country": "Moçambique"},
    {"name": "Fany Pfumo", "followers": 5000, "description": "Cantor moçambicano histórico, pioneiro da marrabenta.", "country": "Moçambique"},
    {"name": "Eyuphuro", "followers": 5000, "description": "Banda moçambicana de música tradicional macua.", "country": "Moçambique"},
    {"name": "MC Roger", "followers": 100000, "description": "Rapper e cantor moçambicano.", "country": "Moçambique"},
    {"name": "Ivan Zulu", "followers": 60000, "description": "Cantor moçambicano de afro-pop e R&B.", "country": "Moçambique"},
    {"name": "Boy Teddy", "followers": 150000, "description": "Cantor moçambicano, um dos artistas mais ouvidos do país.", "country": "Moçambique"},
    {"name": "Messias Maricoa", "followers": 120000, "description": "Cantor moçambicano de afro-pop e amapiano.", "country": "Moçambique"},
    {"name": "Gasso Franco", "followers": 90000, "description": "Cantor moçambicano conhecido como 'Poeta dos 30'.", "country": "Moçambique"},
    {"name": "Samito", "followers": 20000, "description": "Compositor e produtor moçambicano radicado no Canadá.", "country": "Moçambique"},
    {"name": "Yen Sung", "followers": 25000, "description": "DJ, vocalista e produtora moçambicana de house music.", "country": "Moçambique"},
    {"name": "Filomena Maricoa", "followers": 60000, "description": "Cantora moçambicana de kizomba.", "country": "Moçambique"},

    # ---------------- MOÇAMBIQUE - ATLETAS ----------------
    {"name": "Maria Mutola", "followers": 100000, "description": "Ex-atleta moçambicana, campeã olímpica dos 800 metros.", "country": "Moçambique"},
    {"name": "Reinildo Mandava", "followers": 1500000, "description": "Futebolista moçambicano, defesa que joga em clubes europeus de topo.", "country": "Moçambique"},
    {"name": "Alfons Amade", "followers": 50000, "description": "Futebolista moçambicano.", "country": "Moçambique"},
    {"name": "Edmilson Dove", "followers": 40000, "description": "Futebolista moçambicano com passagem por clubes portugueses.", "country": "Moçambique"},
    {"name": "Clésio Bauque", "followers": 30000, "description": "Futebolista moçambicano com passagem por clubes europeus.", "country": "Moçambique"},
    {"name": "Zainadine Júnior", "followers": 25000, "description": "Futebolista moçambicano com passagem por clubes portugueses.", "country": "Moçambique"},
    {"name": "Miro (Amaro Constantino)", "followers": 20000, "description": "Futebolista moçambicano.", "country": "Moçambique"},

    # ---------------- MOÇAMBIQUE - MARCAS E EMPRESAS ----------------
    {"name": "Vodacom Moçambique", "followers": 250000, "description": "Operadora de telecomunicações com presença em Moçambique.", "country": "Moçambique"},
    {"name": "Movitel", "followers": 150000, "description": "Operadora de telecomunicações moçambicana.", "country": "Moçambique"},
    {"name": "mCel", "followers": 100000, "description": "Primeira operadora de telecomunicações móveis de Moçambique.", "country": "Moçambique"},
    {"name": "Millennium bim", "followers": 120000, "description": "Um dos maiores bancos comerciais de Moçambique.", "country": "Moçambique"},
    {"name": "Standard Bank Moçambique", "followers": 90000, "description": "Instituição bancária com operações em Moçambique.", "country": "Moçambique"},
    {"name": "BCI - Banco Comercial e de Investimentos", "followers": 80000, "description": "Banco comercial moçambicano.", "country": "Moçambique"},
    {"name": "Absa Moçambique", "followers": 60000, "description": "Instituição bancária com operações em Moçambique.", "country": "Moçambique"},
    {"name": "FNB Moçambique", "followers": 50000, "description": "Instituição bancária com operações em Moçambique.", "country": "Moçambique"},
    {"name": "Banco Único", "followers": 40000, "description": "Banco comercial moçambicano.", "country": "Moçambique"},
    {"name": "Cervejas de Moçambique", "followers": 100000, "description": "Maior produtora de cerveja e refrigerantes de Moçambique.", "country": "Moçambique"},
    {"name": "2M", "followers": 80000, "description": "Marca de cerveja moçambicana, uma das mais populares do país.", "country": "Moçambique"},
    {"name": "Kero", "followers": 60000, "description": "Cadeia de supermercados moçambicana.", "country": "Moçambique"},
    {"name": "Shoprite Moçambique", "followers": 50000, "description": "Cadeia de supermercados com operações em Moçambique.", "country": "Moçambique"},
    {"name": "Mozal", "followers": 20000, "description": "Fundição de alumínio, uma das maiores indústrias de Moçambique.", "country": "Moçambique"},
    {"name": "Sasol Moçambique", "followers": 15000, "description": "Empresa de energia com operações de gás natural em Moçambique.", "country": "Moçambique"},
    {"name": "LAM - Linhas Aéreas de Moçambique", "followers": 60000, "description": "Companhia aérea de bandeira moçambicana.", "country": "Moçambique"},
    {"name": "TDM - Telecomunicações de Moçambique", "followers": 30000, "description": "Operadora estatal de telecomunicações de Moçambique.", "country": "Moçambique"},
    {"name": "EDM - Electricidade de Moçambique", "followers": 25000, "description": "Empresa pública de eletricidade de Moçambique.", "country": "Moçambique"},
    {"name": "CFM - Portos e Caminhos de Ferro de Moçambique", "followers": 20000, "description": "Empresa pública de portos e caminhos-de-ferro de Moçambique.", "country": "Moçambique"},
    {"name": "Coca-Cola Moçambique (Sabco)", "followers": 40000, "description": "Engarrafadora da Coca-Cola com operações em Moçambique.", "country": "Moçambique"},
    {"name": "Vale Moçambique", "followers": 15000, "description": "Empresa de mineração de carvão com operações em Moçambique.", "country": "Moçambique"},
    {"name": "Kenmare Moma", "followers": 8000, "description": "Empresa de mineração de areias pesadas em Moçambique.", "country": "Moçambique"},

    # ---------------- MOÇAMBIQUE - CLUBES DESPORTIVOS ----------------
    {"name": "Ferroviário de Maputo", "followers": 40000, "description": "Clube de futebol moçambicano, um dos mais tradicionais do país.", "country": "Moçambique"},
    {"name": "Costa do Sol", "followers": 35000, "description": "Clube de futebol moçambicano, um dos mais titulados do país.", "country": "Moçambique"},
    {"name": "Desportivo de Maputo", "followers": 20000, "description": "Clube de futebol moçambicano.", "country": "Moçambique"},
    {"name": "UD Songo", "followers": 15000, "description": "Clube de futebol moçambicano, campeão nacional em anos recentes.", "country": "Moçambique"},

    # ---------------- ÁFRICA DO SUL - CANTORES ----------------
    {"name": "Black Coffee", "followers": 3000000, "description": "DJ e produtor sul-africano de house music com reconhecimento internacional.", "country": "África do Sul"},
    {"name": "Master KG", "followers": 2500000, "description": "Cantor e produtor sul-africano, autor do êxito mundial 'Jerusalema'.", "country": "África do Sul"},
    {"name": "DJ Zinhle", "followers": 3000000, "description": "DJ e empresária sul-africana.", "country": "África do Sul"},
    {"name": "Cassper Nyovest", "followers": 5000000, "description": "Rapper e empresário sul-africano, uma das maiores figuras do hip-hop local.", "country": "África do Sul"},
    {"name": "AKA", "followers": 4000000, "description": "Rapper sul-africano, uma das figuras mais influentes do hip-hop do país.", "country": "África do Sul"},
    {"name": "Nasty C", "followers": 6000000, "description": "Rapper sul-africano com projeção internacional.", "country": "África do Sul"},
    {"name": "Sho Madjozi", "followers": 2000000, "description": "Cantora e rapper sul-africana conhecida pelo seu estilo tsonga.", "country": "África do Sul"},
    {"name": "Tyla", "followers": 8000000, "description": "Cantora sul-africana de amapiano e pop com sucesso internacional.", "country": "África do Sul"},
    {"name": "Focalistic", "followers": 2500000, "description": "Rapper sul-africano de amapiano.", "country": "África do Sul"},
    {"name": "Kabza De Small", "followers": 2000000, "description": "DJ e produtor sul-africano, conhecido como o 'Rei do Amapiano'.", "country": "África do Sul"},
    {"name": "DJ Maphorisa", "followers": 3000000, "description": "DJ e produtor sul-africano de amapiano.", "country": "África do Sul"},
    {"name": "Babes Wodumo", "followers": 2000000, "description": "Cantora sul-africana de gqom.", "country": "África do Sul"},
    {"name": "Zahara", "followers": 1500000, "description": "Cantora sul-africana de folk e soul.", "country": "África do Sul"},
    {"name": "Brenda Fassie", "followers": 500000, "description": "Cantora sul-africana histórica, ícone da música pop africana.", "country": "África do Sul"},
    {"name": "Miriam Makeba", "followers": 400000, "description": "Cantora sul-africana histórica, conhecida internacionalmente como 'Mama Africa'.", "country": "África do Sul"},
    {"name": "Hugh Masekela", "followers": 300000, "description": "Trompetista e cantor sul-africano, figura histórica do jazz africano.", "country": "África do Sul"},
    {"name": "Ladysmith Black Mambazo", "followers": 500000, "description": "Grupo vocal sul-africano de música coral tradicional.", "country": "África do Sul"},
    {"name": "Toya Delazy", "followers": 1000000, "description": "Cantora sul-africana de pop e eletrónica.", "country": "África do Sul"},
    {"name": "Prince Kaybee", "followers": 2000000, "description": "DJ e produtor sul-africano de house music.", "country": "África do Sul"},
    {"name": "Distruction Boyz", "followers": 1500000, "description": "Dupla de DJs sul-africanos de gqom.", "country": "África do Sul"},
    {"name": "Musa Keys", "followers": 1500000, "description": "Cantor e produtor sul-africano de amapiano.", "country": "África do Sul"},
    {"name": "Uncle Waffles", "followers": 1500000, "description": "DJ sul-africana de amapiano com projeção internacional.", "country": "África do Sul"},
    {"name": "Elaine", "followers": 800000, "description": "Cantora sul-africana de R&B e amapiano.", "country": "África do Sul"},
    {"name": "Zonke", "followers": 700000, "description": "Cantora sul-africana de soul e R&B.", "country": "África do Sul"},
    {"name": "Lucky Dube", "followers": 400000, "description": "Cantor sul-africano histórico de reggae.", "country": "África do Sul"},
    {"name": "Yvonne Chaka Chaka", "followers": 1000000, "description": "Cantora sul-africana, uma das figuras mais icónicas da música pop africana.", "country": "África do Sul"},
    {"name": "Mafikizolo", "followers": 1500000, "description": "Dupla musical sul-africana de afro-pop.", "country": "África do Sul"},
    {"name": "DJ Tira", "followers": 1500000, "description": "DJ e produtor sul-africano de gqom e kwaito.", "country": "África do Sul"},
    {"name": "Big Zulu", "followers": 2000000, "description": "Rapper sul-africano conhecido pelo seu estilo em isiZulu.", "country": "África do Sul"},
    {"name": "Emtee", "followers": 3000000, "description": "Rapper sul-africano de hip-hop.", "country": "África do Sul"},
    {"name": "Riky Rick", "followers": 2000000, "description": "Rapper sul-africano, figura influente da cultura hip-hop local.", "country": "África do Sul"},
    {"name": "Simphiwe Dana", "followers": 700000, "description": "Cantora sul-africana de afro-soul.", "country": "África do Sul"},
    {"name": "Loyiso Bala", "followers": 500000, "description": "Cantor sul-africano de gospel e pop.", "country": "África do Sul"},
    {"name": "Lira", "followers": 900000, "description": "Cantora sul-africana de soul e afro-pop.", "country": "África do Sul"},
    {"name": "TKZee", "followers": 400000, "description": "Grupo musical sul-africano de kwaito.", "country": "África do Sul"},
    {"name": "Kwesta", "followers": 2000000, "description": "Rapper sul-africano de hip-hop.", "country": "África do Sul"},
    {"name": "Khuli Chana", "followers": 1500000, "description": "Rapper sul-africano de hip-hop.", "country": "África do Sul"},
    {"name": "HHP", "followers": 500000, "description": "Rapper sul-africano histórico, pioneiro do hip-hop motswako.", "country": "África do Sul"},
    {"name": "Zakes Bantwini", "followers": 1500000, "description": "DJ e produtor sul-africano de house music.", "country": "África do Sul"},
    {"name": "Heavy K", "followers": 1000000, "description": "DJ e produtor sul-africano de house music.", "country": "África do Sul"},
    {"name": "Nadia Nakai", "followers": 3000000, "description": "Rapper sul-africana de hip-hop.", "country": "África do Sul"},
    {"name": "Shekhinah", "followers": 2000000, "description": "Cantora sul-africana de R&B e pop.", "country": "África do Sul"},
    {"name": "Blaq Diamond", "followers": 1000000, "description": "Dupla musical sul-africana de afro-pop.", "country": "África do Sul"},
    {"name": "Lady Zamar", "followers": 1500000, "description": "Cantora sul-africana de R&B e house.", "country": "África do Sul"},
    {"name": "DJ Fresh", "followers": 1000000, "description": "DJ e produtor sul-africano de house music.", "country": "África do Sul"},
    {"name": "Black Motion", "followers": 800000, "description": "Dupla sul-africana de DJs de deep house.", "country": "África do Sul"},
    {"name": "Mi Casa", "followers": 500000, "description": "Banda sul-africana de house e soul.", "country": "África do Sul"},
    {"name": "Freshlyground", "followers": 300000, "description": "Banda sul-africana de afro-fusão, conhecida pela colaboração com Shakira no Mundial de 2010.", "country": "África do Sul"},
    {"name": "Goldfish", "followers": 400000, "description": "Dupla sul-africana de música eletrónica e jazz.", "country": "África do Sul"},
    {"name": "Vusi Nova", "followers": 700000, "description": "Cantor sul-africano de afro-soul.", "country": "África do Sul"},
    {"name": "Berita", "followers": 600000, "description": "Cantora sul-africana de afro-pop e soul.", "country": "África do Sul"},
    {"name": "Amanda Black", "followers": 900000, "description": "Cantora sul-africana de afro-soul.", "country": "África do Sul"},
    {"name": "Msaki", "followers": 500000, "description": "Cantora e compositora sul-africana de folk e soul.", "country": "África do Sul"},
    {"name": "Sjava", "followers": 1500000, "description": "Cantor sul-africano de afro-soul em isiZulu.", "country": "África do Sul"},

    # ---------------- MOÇAMBIQUE - MAIS FUTEBOLISTAS E FIGURAS HISTÓRICAS ----------------
    {"name": "Geny Catamo", "followers": 800000, "description": "Futebolista moçambicano, extremo do Sporting Clube de Portugal.", "country": "Moçambique"},
    {"name": "Chiquinho Conde", "followers": 30000, "description": "Ex-futebolista moçambicano, primeiro jogador do país a atuar legalmente em Portugal após a independência.", "country": "Moçambique"},
    {"name": "Mário Coluna", "followers": 20000, "description": "Ex-futebolista nascido em Moçambique, lenda do Benfica e da Seleção Portuguesa.", "country": "Moçambique"},
    {"name": "Matateu", "followers": 10000, "description": "Ex-futebolista moçambicano histórico, um dos melhores da sua geração.", "country": "Moçambique"},
    {"name": "Hilário", "followers": 8000, "description": "Ex-guarda-redes moçambicano, integrou a seleção portuguesa no Mundial de 1966.", "country": "Moçambique"},
    {"name": "Sérgio Lomba", "followers": 20000, "description": "Futebolista moçambicano com passagem por clubes portugueses.", "country": "Moçambique"},
    {"name": "Bruno Langa", "followers": 15000, "description": "Futebolista moçambicano, lateral com carreira em Portugal.", "country": "Moçambique"},
    {"name": "Fernando Lage", "followers": 5000, "description": "Ex-futebolista moçambicano histórico.", "country": "Moçambique"},
    {"name": "Alberto Massavanhane", "followers": 3000, "description": "Primeiro presidente do Conselho Executivo de Maputo e diplomata moçambicano.", "country": "Moçambique"},
    {"name": "Janet Mondlane", "followers": 5000, "description": "Ativista anti-apartheid e viúva de Eduardo Mondlane.", "country": "Moçambique"},
    {"name": "Carmelita Namashulua", "followers": 8000, "description": "Ministra da Educação e Desenvolvimento Humano de Moçambique.", "country": "Moçambique"},
    {"name": "Francisco Songane", "followers": 3000, "description": "Antigo Ministro da Saúde de Moçambique.", "country": "Moçambique"},
    {"name": "Esperança Bias", "followers": 4000, "description": "Antiga Ministra dos Recursos Minerais de Moçambique.", "country": "Moçambique"},
    {"name": "Eldevina Materula", "followers": 3000, "description": "Oboísta e professora de música moçambicana.", "country": "Moçambique"},

    # ---------------- MOÇAMBIQUE - MAIS MÚSICOS ----------------
    {"name": "Xidiminguana", "followers": 20000, "description": "Banda moçambicana de música tradicional changana.", "country": "Moçambique"},
    {"name": "Preto Show", "followers": 80000, "description": "Cantor e produtor moçambicano de hip-hop e afrobeat.", "country": "Moçambique"},
    {"name": "Laylizzy", "followers": 100000, "description": "Rapper moçambicano de hip-hop.", "country": "Moçambique"},

    # ---------------- MOÇAMBIQUE - MEDIA E INSTITUIÇÕES ----------------
    {"name": "Rádio Moçambique", "followers": 100000, "description": "Emissora de rádio pública e nacional de Moçambique.", "country": "Moçambique"},
    {"name": "TVM - Televisão de Moçambique", "followers": 150000, "description": "Canal de televisão público de Moçambique.", "country": "Moçambique"},
    {"name": "STV - Soico TV", "followers": 200000, "description": "Canal de televisão privado moçambicano.", "country": "Moçambique"},
    {"name": "Miramar Televisão", "followers": 100000, "description": "Canal de televisão privado moçambicano.", "country": "Moçambique"},
    {"name": "Jornal Notícias", "followers": 80000, "description": "Um dos principais jornais diários de Moçambique.", "country": "Moçambique"},
    {"name": "O País", "followers": 100000, "description": "Jornal moçambicano de circulação nacional.", "country": "Moçambique"},
    {"name": "Universidade Eduardo Mondlane", "followers": 60000, "description": "Principal e mais antiga universidade pública de Moçambique.", "country": "Moçambique"},
    {"name": "ISCTEM", "followers": 20000, "description": "Instituto Superior de Ciências e Tecnologia de Moçambique, universidade privada.", "country": "Moçambique"},
    {"name": "Textáfrica", "followers": 5000, "description": "Antiga fábrica têxtil moçambicana, histórica na indústria do país.", "country": "Moçambique"},
    {"name": "Intelec Holdings", "followers": 5000, "description": "Grupo empresarial moçambicano com participações em vários setores.", "country": "Moçambique"},

    # ---------------- ÁFRICA DO SUL - MAIS CANTORES ----------------
    {"name": "Rebecca Malope", "followers": 600000, "description": "Cantora sul-africana de gospel, uma das mais vendidas do género no país.", "country": "África do Sul"},
    {"name": "Vusi Mahlasela", "followers": 300000, "description": "Cantor e compositor sul-africano de folk.", "country": "África do Sul"},
    {"name": "PJ Powers", "followers": 200000, "description": "Cantora sul-africana de rock e pop.", "country": "África do Sul"},
    {"name": "Bongo Maffin", "followers": 300000, "description": "Grupo musical sul-africano de kwaito.", "country": "África do Sul"},
    {"name": "Ringo Madlingozi", "followers": 400000, "description": "Cantor sul-africano de afro-soul.", "country": "África do Sul"},
    {"name": "Chicco Twala", "followers": 200000, "description": "Cantor e produtor sul-africano, figura histórica do bubblegum pop.", "country": "África do Sul"},
    {"name": "Brothers of Peace", "followers": 150000, "description": "Grupo musical sul-africano de kwaito.", "country": "África do Sul"},
    {"name": "Arthur Mafokate", "followers": 300000, "description": "Cantor sul-africano, conhecido como o 'Rei do Kwaito'.", "country": "África do Sul"},
    {"name": "DJ Sbu", "followers": 1000000, "description": "DJ e empresário sul-africano.", "country": "África do Sul"},
    {"name": "Oskido", "followers": 800000, "description": "DJ e produtor sul-africano, figura influente da house music.", "country": "África do Sul"},
    {"name": "Danny K", "followers": 500000, "description": "Cantor sul-africano de R&B e pop.", "country": "África do Sul"},
    {"name": "Karen Zoid", "followers": 300000, "description": "Cantora sul-africana de rock.", "country": "África do Sul"},
    {"name": "Jack Parow", "followers": 400000, "description": "Rapper sul-africano de estilo zef.", "country": "África do Sul"},
    {"name": "Die Antwoord", "followers": 2000000, "description": "Grupo musical sul-africano de rap-rave, conhecido internacionalmente.", "country": "África do Sul"},
    {"name": "Prime Circle", "followers": 300000, "description": "Banda sul-africana de rock alternativo.", "country": "África do Sul"},
    {"name": "Majozi", "followers": 400000, "description": "Cantor sul-africano de folk-pop.", "country": "África do Sul"},
    {"name": "Nathi", "followers": 600000, "description": "Cantor sul-africano de afro-soul.", "country": "África do Sul"},
    {"name": "Langa Mavuso", "followers": 300000, "description": "Cantor sul-africano de soul.", "country": "África do Sul"},
    {"name": "Thandiswa Mazwai", "followers": 700000, "description": "Cantora sul-africana de afro-soul, ex-vocalista dos Bongo Maffin.", "country": "África do Sul"},
    {"name": "Bongeziwe Mabandla", "followers": 300000, "description": "Cantor sul-africano de folk contemporâneo.", "country": "África do Sul"},
    {"name": "Nomfundo Moh", "followers": 700000, "description": "Cantora sul-africana de afro-soul.", "country": "África do Sul"},
    {"name": "K.O", "followers": 2000000, "description": "Rapper sul-africano de hip-hop.", "country": "África do Sul"},
    {"name": "Gigi Lamayne", "followers": 1000000, "description": "Rapper sul-africana de hip-hop.", "country": "África do Sul"},
    {"name": "Moozlie", "followers": 1000000, "description": "Rapper sul-africana de hip-hop.", "country": "África do Sul"},
    {"name": "Reason", "followers": 800000, "description": "Rapper sul-africano de hip-hop.", "country": "África do Sul"},
    {"name": "YoungstaCPT", "followers": 400000, "description": "Rapper sul-africano da Cidade do Cabo.", "country": "África do Sul"},
    {"name": "Costa Titch", "followers": 1500000, "description": "Rapper sul-africano, figura popular do amapiano e hip-hop.", "country": "África do Sul"},
    {"name": "Zola 7", "followers": 500000, "description": "Rapper e ator sul-africano de kwaito.", "country": "África do Sul"},
    {"name": "Skwatta Kamp", "followers": 300000, "description": "Grupo sul-africano de hip-hop.", "country": "África do Sul"},
    {"name": "Watershed", "followers": 250000, "description": "Banda sul-africana de pop-rock.", "country": "África do Sul"},

    # ---------------- ÚLTIMAS ADIÇÕES ----------------
    {"name": "Trevor Noah", "followers": 15000000, "description": "Comediante e apresentador sul-africano, antigo apresentador do The Daily Show.", "country": "África do Sul"},
    {"name": "Loyiso Gola", "followers": 400000, "description": "Comediante sul-africano.", "country": "África do Sul"},
    {"name": "Bonang Matheba", "followers": 6000000, "description": "Apresentadora e empresária sul-africana.", "country": "África do Sul"},
    {"name": "Somizi Mhlongo", "followers": 4000000, "description": "Apresentador e coreógrafo sul-africano.", "country": "África do Sul"},
    {"name": "Kabelo Mabalane", "followers": 1000000, "description": "Cantor sul-africano, ex-integrante do grupo TKZee.", "country": "África do Sul"},
    {"name": "Lebo Mathosa", "followers": 300000, "description": "Cantora sul-africana histórica, ex-vocalista do grupo Boom Shaka.", "country": "África do Sul"},
    {"name": "Petromoc", "followers": 20000, "description": "Empresa petrolífera estatal de distribuição de combustíveis em Moçambique.", "country": "Moçambique"},
    {"name": "Banco Terra", "followers": 15000, "description": "Banco comercial moçambicano voltado para o setor agrícola.", "country": "Moçambique"},
    {"name": "Rádio Cidade de Maputo", "followers": 40000, "description": "Estação de rádio privada moçambicana.", "country": "Moçambique"},
]

# Contador de referência
if __name__ == "__main__":
    print(f"Total de entradas: {len(data)}")
